version: '3.3'
services:
  postgresql:
    image: postgres:latest
    restart: always
    container_name: postgresql
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5438:5432"
    volumes:
      - ./scripts/sql.sql:/docker-entrypoint-initdb.d/sql.sql
      - ./data:/var/lib/postgresql/data/

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

