version: '3.3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    hostname: "api.local"
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

volumes:
  postgresql:
    driver: local
  database-data: